// ─── Mock Practitioners ───────────────────────────────────────────────────────
export const MOCK_PRACTITIONERS = [
  {
    id: 1,
    name: 'Dr. Sarah Jenkins',
    discipline: 'Physiotherapy',
    location: 'Melbourne CBD',
    suburb: 'Melbourne',
    telehealth: true,
    verified: true,
    availabilityTypes: ['after-hours', 'weekends'],
    availability: 'After-Hours & Weekends',
    rating: 4.9,
    reviews: 124,
    image: 'https://i.pravatar.cc/150?u=sarah',
    bio: 'Specialising in musculoskeletal rehabilitation and sports injuries. 12+ years experience.',
    fee: 150,
    nextSlots: ['Tonight 6:30 PM', 'Sat 9:00 AM', 'Sun 11:00 AM'],
    languages: ['English'],
  },
  {
    id: 2,
    name: 'James O\'Connor',
    discipline: 'Psychology',
    location: 'Sydney (Remote)',
    suburb: 'Sydney',
    telehealth: true,
    verified: true,
    availabilityTypes: ['after-hours', 'weekends'],
    availability: 'Weekends & After-Hours',
    rating: 4.8,
    reviews: 89,
    image: 'https://i.pravatar.cc/150?u=james',
    bio: 'Cognitive behavioural therapy specialist. AHPRA registered. Telehealth nationwide.',
    fee: 180,
    nextSlots: ['Tomorrow 7:00 PM', 'Sat 10:00 AM'],
    languages: ['English', 'Spanish'],
  },
  {
    id: 3,
    name: 'Dr. Emily Chen',
    discipline: 'Occupational Therapy',
    location: 'Brisbane North',
    suburb: 'Brisbane',
    telehealth: false,
    verified: false,
    availabilityTypes: ['weekends'],
    availability: 'Weekends Only',
    rating: 4.5,
    reviews: 32,
    image: 'https://i.pravatar.cc/150?u=emily',
    bio: 'Paediatric OT with NDIS experience. Currently awaiting compliance verification.',
    fee: 130,
    nextSlots: ['Sun 9:00 AM', 'Sun 11:30 AM'],
    languages: ['English', 'Mandarin'],
  },
  {
    id: 4,
    name: 'Marcus Thompson',
    discipline: 'Speech Therapy',
    location: 'Perth CBD',
    suburb: 'Perth',
    telehealth: true,
    verified: true,
    availabilityTypes: ['after-hours'],
    availability: 'After-Hours (6pm–9pm)',
    rating: 4.7,
    reviews: 61,
    image: 'https://i.pravatar.cc/150?u=marcus',
    bio: 'Adult and paediatric speech pathologist. Focus on fluency and voice disorders.',
    fee: 140,
    nextSlots: ['Tonight 7:00 PM', 'Tomorrow 6:30 PM'],
    languages: ['English'],
  },
  {
    id: 5,
    name: 'Dr. Priya Nair',
    discipline: 'Nutrition & Dietetics',
    location: 'Adelaide (Remote)',
    suburb: 'Adelaide',
    telehealth: true,
    verified: true,
    availabilityTypes: ['after-hours', 'weekends'],
    availability: 'After-Hours & Weekends',
    rating: 4.9,
    reviews: 203,
    image: 'https://i.pravatar.cc/150?u=priya',
    bio: 'Accredited Practising Dietitian. Specialising in chronic disease, gut health & NDIS.',
    fee: 120,
    nextSlots: ['Tomorrow 8:00 PM', 'Sat 8:00 AM', 'Sat 2:00 PM'],
    languages: ['English', 'Hindi', 'Malayalam'],
  },
  {
    id: 6,
    name: 'Ben Kowalski',
    discipline: 'Physiotherapy',
    location: 'Canberra',
    suburb: 'Canberra',
    telehealth: false,
    verified: true,
    availabilityTypes: ['weekends'],
    availability: 'Weekends Only',
    rating: 4.6,
    reviews: 45,
    image: 'https://i.pravatar.cc/150?u=ben',
    bio: 'Sports and exercise physiotherapist. Dry needling and manual therapy certified.',
    fee: 160,
    nextSlots: ['Sat 10:00 AM', 'Sat 1:00 PM', 'Sun 10:00 AM'],
    languages: ['English', 'Polish'],
  },
];

// ─── Filter Options ───────────────────────────────────────────────────────────
export const DISCIPLINES = [
  'All Disciplines',
  'Physiotherapy',
  'Psychology',
  'Occupational Therapy',
  'Speech Therapy',
  'Nutrition & Dietetics',
  'Exercise Physiology',
  'Social Work',
];

export const AVAILABILITY_OPTIONS = [
  { label: 'All Availability', value: 'all' },
  { label: 'After-Hours', value: 'after-hours' },
  { label: 'Weekends', value: 'weekends' },
];

export const LOCATIONS = [
  'All Locations',
  'Melbourne',
  'Sydney',
  'Brisbane',
  'Perth',
  'Adelaide',
  'Canberra',
];

// ─── Time Slots for Booking ───────────────────────────────────────────────────
export const TIME_SLOTS_BY_DATE = {
  Today: ['18:00', '18:30', '19:00', '19:30', '20:00'],
  Tomorrow: ['18:30', '19:00', '19:30', '20:00', '20:30'],
  Saturday: ['09:00', '09:30', '10:00', '11:00', '11:30', '14:00'],
  Sunday: ['09:00', '10:00', '11:00', '11:30'],
};
