export const FUNDING_PATHWAYS = [
  'NDIS',
  'Medicare',
  'My Aged Care',
  'Private Health Fund',
  'Veterans’ Affairs',
];

export const DISCIPLINES = [
  'All',
  'Psychologists',
  'Clinical Psychologists',
  'Neuropsychologists',
  'Counsellors',
  'Psychotherapists',
  'Social Workers, AASW-accredited',
  'Mental Health Social Workers',
  'Art Therapists',
  'Music Therapists',
  'Drama Therapists',
  'Play Therapists',
];

export const MOCK_PRACTITIONERS = [
  {
    id: 'demo-1',
    name: 'Amelia Hart',
    discipline: 'Clinical Psychologists',
    gender: 'Female',
    location: 'Brunswick, VIC',
    postcode: '3056',
    travelArea: 'Clinic, telehealth and mobile sessions within 20 km',
    travelsToPostcodes: ['3056', '3057', '3070', '3071'],
    mobile: true,
    telehealth: true,
    verified: true,
    afterHours: true,
    weekends: true,
    fundingOptions: ['NDIS', 'Medicare', 'Private Health Fund'],
    rating: 4.9,
    reviews: 64,
    image: 'https://i.pravatar.cc/150?u=amelia-beyond5',
    bio: 'Clinical psychologist supporting children, families and adults with flexible appointments and NDIS-aligned therapy goals.',
    fee: 210,
    sploseStatus: 'Splose calendar ready: live slot visibility pending API connection',
  },
  {
    id: 'demo-2',
    name: 'Jordan Lee',
    discipline: 'Mental Health Social Workers',
    gender: 'Male',
    location: 'Mobile practitioner, North Melbourne',
    postcode: '3051',
    travelArea: 'Travels across inner north and western suburbs',
    travelsToPostcodes: ['3000', '3011', '3031', '3051', '3056'],
    mobile: true,
    telehealth: true,
    verified: true,
    afterHours: true,
    weekends: false,
    fundingOptions: ['NDIS', 'Veterans’ Affairs', 'Medicare'],
    rating: 4.8,
    reviews: 42,
    image: 'https://i.pravatar.cc/150?u=jordan-beyond5',
    bio: 'Accredited mental health social worker providing practical therapy support for participants, carers and referrers.',
    fee: 180,
    sploseStatus: 'Splose-managed availability: next mobile sessions visible after integration',
  },
  {
    id: 'demo-3',
    name: 'Maya Singh',
    discipline: 'Art Therapists',
    gender: 'Female',
    location: 'Northcote, VIC',
    postcode: '3070',
    travelArea: 'Clinic and local school/community visits',
    travelsToPostcodes: ['3070', '3071', '3072', '3056'],
    mobile: true,
    telehealth: false,
    verified: true,
    afterHours: false,
    weekends: true,
    fundingOptions: ['NDIS', 'Private Health Fund', 'My Aged Care'],
    rating: 4.7,
    reviews: 31,
    image: 'https://i.pravatar.cc/150?u=maya-beyond5',
    bio: 'Registered art therapist working with children, young people and families through creative therapeutic practice.',
    fee: 155,
    sploseStatus: 'Splose calendar mapping needed for group and individual sessions',
  },
  {
    id: 'demo-4',
    name: 'Noah Clarke',
    discipline: 'Neuropsychologists',
    gender: 'Male',
    location: 'Melbourne CBD, VIC',
    postcode: '3000',
    travelArea: 'Clinic-based assessments with telehealth follow-up',
    travelsToPostcodes: ['3000', '3002', '3003', '3051'],
    mobile: false,
    telehealth: true,
    verified: true,
    afterHours: false,
    weekends: false,
    fundingOptions: ['Medicare', 'Private Health Fund', 'Veterans’ Affairs'],
    rating: 4.9,
    reviews: 76,
    image: 'https://i.pravatar.cc/150?u=noah-beyond5',
    bio: 'Neuropsychologist offering cognitive assessment, reports and therapy planning for adults and older people.',
    fee: 260,
    sploseStatus: 'Splose availability requires assessment-length appointment templates',
  },
  {
    id: 'demo-5',
    name: 'Olivia Tran',
    discipline: 'Counsellors',
    gender: 'Female',
    location: 'Footscray, VIC',
    postcode: '3011',
    travelArea: 'Telehealth and mobile sessions within 15 km',
    travelsToPostcodes: ['3011', '3012', '3020', '3032'],
    mobile: true,
    telehealth: true,
    verified: true,
    afterHours: true,
    weekends: true,
    fundingOptions: ['NDIS', 'Private Health Fund'],
    rating: 4.6,
    reviews: 28,
    image: 'https://i.pravatar.cc/150?u=olivia-beyond5',
    bio: 'Counsellor supporting anxiety, family change, grief and culturally responsive therapy goals.',
    fee: 140,
    sploseStatus: 'Splose calendar ready for after-hours booking windows',
  },
  {
    id: 'demo-6',
    name: 'Sophie Williams',
    discipline: 'Play Therapists',
    gender: 'Female',
    location: 'Preston, VIC',
    postcode: '3072',
    travelArea: 'Mobile play therapy to homes, schools and community settings',
    travelsToPostcodes: ['3056', '3070', '3071', '3072', '3083'],
    mobile: true,
    telehealth: false,
    verified: true,
    afterHours: false,
    weekends: true,
    fundingOptions: ['NDIS', 'My Aged Care'],
    rating: 4.8,
    reviews: 39,
    image: 'https://i.pravatar.cc/150?u=sophie-beyond5',
    bio: 'Play therapist supporting children and families with flexible in-person sessions across natural environments.',
    fee: 165,
    sploseStatus: 'Splose integration pending travel buffer rules',
  },
];

export const AVAILABILITY_OPTIONS = [
  { label: 'All Availability', value: 'all' },
  { label: 'After-Hours', value: 'after-hours' },
  { label: 'Weekends', value: 'weekends' },
];

export const LOCATIONS = [
  'All Locations',
  'Melbourne',
  'Brunswick',
  'Northcote',
  'Footscray',
  'Preston',
];

export const TIME_SLOTS_BY_DATE = {
  Today: ['18:00', '18:30', '19:00', '19:30', '20:00'],
  Tomorrow: ['18:30', '19:00', '19:30', '20:00', '20:30'],
  Saturday: ['09:00', '09:30', '10:00', '11:00', '11:30', '14:00'],
  Sunday: ['09:00', '10:00', '11:00', '11:30'],
};
